export const ZATCA_DOCUMENT_TYPE = {
  INVOICE: "invoice",
  CREDIT_NOTE: "credit_note",
  DEBIT_NOTE: "debit_note",
} as const;

export const ZATCA_DOCUMENT_TYPES = [
  ZATCA_DOCUMENT_TYPE.INVOICE,
  ZATCA_DOCUMENT_TYPE.CREDIT_NOTE,
  ZATCA_DOCUMENT_TYPE.DEBIT_NOTE,
] as const;

export type ZatcaDocumentType = (typeof ZATCA_DOCUMENT_TYPES)[number];

export const ZATCA_LIFECYCLE_SOURCE_TYPE = {
  ORDER: "order",
  REFUND: "refund",
  RETURN: "return",
  ORDER_CANCEL: "order_cancel",
  ORDER_EDIT: "order_edit",
} as const;

export const ZATCA_LIFECYCLE_SOURCE_TYPES = [
  ZATCA_LIFECYCLE_SOURCE_TYPE.ORDER,
  ZATCA_LIFECYCLE_SOURCE_TYPE.REFUND,
  ZATCA_LIFECYCLE_SOURCE_TYPE.RETURN,
  ZATCA_LIFECYCLE_SOURCE_TYPE.ORDER_CANCEL,
  ZATCA_LIFECYCLE_SOURCE_TYPE.ORDER_EDIT,
] as const;

export type ZatcaLifecycleSourceType =
  (typeof ZATCA_LIFECYCLE_SOURCE_TYPES)[number];

export const ZATCA_INVOICE_STATUS = {
  PENDING: "pending",
  REPORTED: "reported",
  REJECTED: "rejected",
  FAILED: "failed",
} as const;

export const ZATCA_INVOICE_STATUSES = [
  ZATCA_INVOICE_STATUS.PENDING,
  ZATCA_INVOICE_STATUS.REPORTED,
  ZATCA_INVOICE_STATUS.REJECTED,
  ZATCA_INVOICE_STATUS.FAILED,
] as const;

export type ZatcaInvoiceStatus = (typeof ZATCA_INVOICE_STATUSES)[number];

export const ZATCA_INVOICE_TYPE_CODE = {
  INVOICE: "388",
  CREDIT_NOTE: "381",
  DEBIT_NOTE: "383",
} as const;

export const ZATCA_INVOICE_TYPE_CODES = [
  ZATCA_INVOICE_TYPE_CODE.INVOICE,
  ZATCA_INVOICE_TYPE_CODE.CREDIT_NOTE,
  ZATCA_INVOICE_TYPE_CODE.DEBIT_NOTE,
] as const;

export const ZATCA_INVOICE_TYPE = {
  SIMPLIFIED: "simplified",
} as const;

export const ZATCA_INVOICE_TYPES = [ZATCA_INVOICE_TYPE.SIMPLIFIED] as const;

export const ZATCA_CURRENCY = {
  SAR: "SAR",
  SAR_LOWERCASE: "sar",
} as const;

export const ZATCA_COUNTRY_CODE = {
  SAUDI_ARABIA: "SA",
} as const;

export const ZATCA_TAX_SCHEME = {
  VAT: "VAT",
} as const;

export const ZATCA_TAX_CATEGORY = {
  STANDARD_RATE: "S",
  OUT_OF_SCOPE: "O",
} as const;

export const ZATCA_PAYMENT_MEANS_CODE = {
  CASH: "10",
} as const;

export const ZATCA_INVOICE_TYPE_NAME = {
  PLAIN_SIMPLIFIED: "0200000",
} as const;

export const ZATCA_VAT = {
  DEFAULT_PERCENT: 15,
  ZERO_PERCENT: 0,
} as const;

export const ZATCA_ALLOWANCE_CHARGE_REASON = {
  DISCOUNT: "discount",
  SHIPPING: "shipping",
} as const;

export const ZATCA_NOTE_REASON = {
  REFUND: "Refund",
  RETURN_RECEIVED: "Return received",
  ORDER_CANCELLED: "Order cancelled",
  ORDER_EDIT_DECREASE: "Order edit decrease",
  ORDER_EDIT_INCREASE: "Order edit increase",
} as const;

export const ZATCA_ERROR_CODE = {
  RECONCILIATION_MISMATCH: "reconciliation_mismatch",
  OVER_CREDIT: "zatca_over_credit",
  REPORTING_WINDOW_EXPIRED: "reporting_window_expired",
} as const;

export const ZATCA_MEDUSA_EVENT = {
  PAYMENT_CAPTURED: "payment.captured",
  PAYMENT_REFUNDED: "payment.refunded",
  ORDER_PLACED: "order.placed",
  ORDER_CANCELED: "order.canceled",
  ORDER_RETURN_RECEIVED: "order.return_received",
  ORDER_EDIT_CONFIRMED: "order-edit.confirmed",
} as const;

export const ZATCA_QUERY_ENTITY = {
  ORDER: "order",
  PAYMENT: "payment",
  RETURN: "return",
  ZATCA_INVOICE: "zatca_invoice",
} as const;

export const ZATCA_TABLE = {
  INVOICE: ZATCA_QUERY_ENTITY.ZATCA_INVOICE,
} as const;

export const ZATCA_QUERY_FIELD = {
  ORDER_ID: "id",
  ORDER_DISPLAY_ID: "display_id",
  ORDER_CURRENCY_CODE: "currency_code",
  ORDER_STATUS: "status",
  ORDER_TOTAL: "total",
  ORDER_TAX_TOTAL: "tax_total",
  ORDER_SUBTOTAL: "subtotal",
  ORDER_DISCOUNT_TOTAL: "discount_total",
  ORDER_SHIPPING_TOTAL: "shipping_total",
  ORDER_ITEM_TOTAL: "item_total",
  ORDER_SUMMARY: "summary.*",
  ITEM_ID: "items.id",
  ITEM_TITLE: "items.title",
  ITEM_QUANTITY: "items.quantity",
  ITEM_DETAIL_QUANTITY: "items.detail.quantity",
  ITEM_UNIT_PRICE: "items.unit_price",
  ITEM_IS_TAX_INCLUSIVE: "items.is_tax_inclusive",
  ITEM_SUBTOTAL: "items.subtotal",
  ITEM_TOTAL: "items.total",
  ITEM_TAX_TOTAL: "items.tax_total",
  ITEM_DISCOUNT_TOTAL: "items.discount_total",
  ITEM_DISCOUNT_TAX_TOTAL: "items.discount_tax_total",
  ITEM_TAX_RATE: "items.tax_lines.rate",
  ITEM_TAX_TOTAL_FIELD: "items.tax_lines.total",
  ITEM_TAX_SUBTOTAL: "items.tax_lines.subtotal",
  SHIPPING_ID: "shipping_methods.id",
  SHIPPING_AMOUNT: "shipping_methods.amount",
  SHIPPING_IS_TAX_INCLUSIVE: "shipping_methods.is_tax_inclusive",
  SHIPPING_SUBTOTAL: "shipping_methods.subtotal",
  SHIPPING_TOTAL: "shipping_methods.total",
  SHIPPING_TAX_TOTAL: "shipping_methods.tax_total",
  SHIPPING_DISCOUNT_TOTAL: "shipping_methods.discount_total",
  SHIPPING_DISCOUNT_TAX_TOTAL: "shipping_methods.discount_tax_total",
  SHIPPING_TAX_RATE: "shipping_methods.tax_lines.rate",
  SHIPPING_TAX_TOTAL_FIELD: "shipping_methods.tax_lines.total",
  PAYMENT_ID: "id",
  PAYMENT_COLLECTION_ORDER_ID: "payment_collection.order.id",
  REFUND_ID: "refunds.id",
  REFUND_AMOUNT: "refunds.amount",
  REFUND_CREATED_AT: "refunds.created_at",
  RETURN_ID: "id",
  RETURN_ORDER_ID: "order_id",
  RETURN_REASON: "reason",
  RETURN_ITEM_ID: "items.item_id",
  RETURN_ITEM_QUANTITY: "items.quantity",
  RETURN_ITEM_RECEIVED_QUANTITY: "items.received_quantity",
  LINKED_ZATCA_INVOICE_ID: "zatca_invoices.id",
  LINKED_ZATCA_INVOICE_STATUS: "zatca_invoices.status",
  LINKED_ZATCA_INVOICE_DOCUMENT_TYPE: "zatca_invoices.document_type",
  LINKED_ORDER_ID: "order.id",
  LINKED_ORDER_EMAIL: "order.email",
  ZATCA_INVOICE_ID: "id",
  ZATCA_INVOICE_ICV: "icv",
} as const;

export const ZATCA_ORIGINAL_INVOICE_ORDER_FIELDS = [
  ZATCA_QUERY_FIELD.ORDER_ID,
  ZATCA_QUERY_FIELD.ORDER_DISPLAY_ID,
  ZATCA_QUERY_FIELD.ORDER_CURRENCY_CODE,
  ZATCA_QUERY_FIELD.ORDER_STATUS,
  ZATCA_QUERY_FIELD.ORDER_TOTAL,
  ZATCA_QUERY_FIELD.ORDER_TAX_TOTAL,
  ZATCA_QUERY_FIELD.ORDER_SUBTOTAL,
  ZATCA_QUERY_FIELD.ORDER_DISCOUNT_TOTAL,
  ZATCA_QUERY_FIELD.ORDER_SHIPPING_TOTAL,
  ZATCA_QUERY_FIELD.ORDER_ITEM_TOTAL,
  ZATCA_QUERY_FIELD.ORDER_SUMMARY,
  ZATCA_QUERY_FIELD.ITEM_ID,
  ZATCA_QUERY_FIELD.ITEM_TITLE,
  ZATCA_QUERY_FIELD.ITEM_QUANTITY,
  ZATCA_QUERY_FIELD.ITEM_DETAIL_QUANTITY,
  ZATCA_QUERY_FIELD.ITEM_UNIT_PRICE,
  ZATCA_QUERY_FIELD.ITEM_IS_TAX_INCLUSIVE,
  ZATCA_QUERY_FIELD.ITEM_SUBTOTAL,
  ZATCA_QUERY_FIELD.ITEM_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_TAX_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_DISCOUNT_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_DISCOUNT_TAX_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_TAX_RATE,
  ZATCA_QUERY_FIELD.ITEM_TAX_TOTAL_FIELD,
  ZATCA_QUERY_FIELD.ITEM_TAX_SUBTOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_ID,
  ZATCA_QUERY_FIELD.SHIPPING_AMOUNT,
  ZATCA_QUERY_FIELD.SHIPPING_IS_TAX_INCLUSIVE,
  ZATCA_QUERY_FIELD.SHIPPING_SUBTOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_TOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_TAX_TOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_DISCOUNT_TOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_DISCOUNT_TAX_TOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_TAX_RATE,
  ZATCA_QUERY_FIELD.SHIPPING_TAX_TOTAL_FIELD,
] as const;

export const ZATCA_ORDER_EDIT_ORDER_FIELDS = [
  ZATCA_QUERY_FIELD.ORDER_ID,
  ZATCA_QUERY_FIELD.ORDER_CURRENCY_CODE,
  ZATCA_QUERY_FIELD.ORDER_STATUS,
  ZATCA_QUERY_FIELD.ORDER_TOTAL,
  ZATCA_QUERY_FIELD.ORDER_TAX_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_ID,
  ZATCA_QUERY_FIELD.ITEM_TITLE,
  ZATCA_QUERY_FIELD.ITEM_QUANTITY,
  ZATCA_QUERY_FIELD.ITEM_DETAIL_QUANTITY,
  ZATCA_QUERY_FIELD.ITEM_UNIT_PRICE,
  ZATCA_QUERY_FIELD.ITEM_IS_TAX_INCLUSIVE,
  ZATCA_QUERY_FIELD.ITEM_SUBTOTAL,
  ZATCA_QUERY_FIELD.ITEM_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_TAX_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_DISCOUNT_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_DISCOUNT_TAX_TOTAL,
  ZATCA_QUERY_FIELD.ITEM_TAX_RATE,
  ZATCA_QUERY_FIELD.ITEM_TAX_TOTAL_FIELD,
  ZATCA_QUERY_FIELD.ITEM_TAX_SUBTOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_TOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_TAX_TOTAL,
  ZATCA_QUERY_FIELD.SHIPPING_TAX_RATE,
] as const;

export const ZATCA_PAYMENT_REFUND_FIELDS = [
  ZATCA_QUERY_FIELD.PAYMENT_ID,
  ZATCA_QUERY_FIELD.REFUND_ID,
  ZATCA_QUERY_FIELD.REFUND_AMOUNT,
  ZATCA_QUERY_FIELD.REFUND_CREATED_AT,
  ZATCA_QUERY_FIELD.PAYMENT_COLLECTION_ORDER_ID,
] as const;

export const ZATCA_PAYMENT_ORDER_FIELDS = [
  ZATCA_QUERY_FIELD.PAYMENT_ID,
  ZATCA_QUERY_FIELD.PAYMENT_COLLECTION_ORDER_ID,
] as const;

export const ZATCA_RETURN_FIELDS = [
  ZATCA_QUERY_FIELD.RETURN_ID,
  ZATCA_QUERY_FIELD.RETURN_ORDER_ID,
  ZATCA_QUERY_FIELD.RETURN_REASON,
  ZATCA_QUERY_FIELD.RETURN_ITEM_ID,
  ZATCA_QUERY_FIELD.RETURN_ITEM_QUANTITY,
  ZATCA_QUERY_FIELD.RETURN_ITEM_RECEIVED_QUANTITY,
] as const;
