import {
  ALLOWANCE_TAX_CATEGORY_TEMPLATE,
  CUSTOMER_PARTY_TEMPLATE,
  INVOICE_LINE_TEMPLATE,
  SIMPLIFIED_INVOICE_TEMPLATE,
  TAX_SUBTOTAL_TEMPLATE,
} from "./templates/simplified-invoice";

/**
 * Simplified (B2C) UBL 2.1 invoice builder.
 *
 * The template is generated byte-for-byte from the ZATCA SDK golden sample
 * (see templates/simplified-invoice.ts); the builder only substitutes values
 * and repeats blocks, so for the golden sample's data the output canonicalizes
 * to the exact bytes the SDK validator hashed (ADR-0007 byte-match gate).
 *
 * All money is integer halalas (CONTRACT.md §Money); decimal strings are
 * produced by exact integer formatting, never float arithmetic.
 */

export interface ZatcaPartyAddress {
  street: string;
  building: string;
  citySubdivision: string;
  city: string;
  postalZone: string;
}

export interface ZatcaSupplier extends ZatcaPartyAddress {
  /** Commercial registration number (CRN). */
  crn: string;
  /** 15-digit VAT registration number. */
  vatNumber: string;
  /** Registered organization name. */
  name: string;
}

export interface ZatcaCustomer extends ZatcaPartyAddress {
  vatNumber: string;
  name: string;
}

export interface ZatcaInvoiceLine {
  /** Sequential line id, 1-based. */
  id: number;
  name: string;
  /** Integer quantity (UBL renders it with 6 decimals). */
  quantity: number;
  /** Unit price in integer halalas. */
  unitPriceHalalas: number;
  /** VAT percent, e.g. 15. Zero renders category "O" (out of scope). */
  vatPercent: number;
}

export interface SimplifiedInvoiceProps {
  /** Invoice serial number (cbc:ID), e.g. "SME00010". */
  serialNumber: string;
  /** Invoice UUID (KSA-1). */
  uuid: string;
  /** Issue date, YYYY-MM-DD. */
  issueDate: string;
  /** Issue time, HH:mm:ss. */
  issueTime: string;
  /** KSA-2 invoice subtype flags; defaults to plain simplified ("0200000"). */
  invoiceTypeName?: string;
  /** UN/CEFACT 1001 code; 388 = tax invoice (default). */
  invoiceTypeCode?: string;
  note?: { languageId: string; text: string };
  /** Invoice counter value (ICV, KSA-16). */
  icv: number;
  /** Previous invoice hash (PIH, KSA-13). */
  pih: string;
  supplier: ZatcaSupplier;
  customer?: ZatcaCustomer;
  /** UN/ECE 4461 payment means code; "10" = cash. */
  paymentMeansCode?: string;
  /**
   * Serial of the invoice being credited/debited (BR-KSA-56). Required for
   * credit (381) and debit (383) notes; omit for plain invoices.
   */
  billingReference?: string;
  /** Reason for the credit/debit note (KSA-10, BR-KSA-17). */
  instructionNote?: string;
  lines: ZatcaInvoiceLine[];
}

export interface BuiltSimplifiedInvoice {
  /** Unsigned invoice XML (signing placeholders intact, QR placeholder intact). */
  xml: string;
  /** Σ line extension amounts, halalas (BT-106/BT-109). */
  taxExclusiveHalalas: number;
  /** Total VAT, halalas (BT-110). */
  taxHalalas: number;
  /** Tax-inclusive total, halalas (BT-112/BT-115). */
  taxInclusiveHalalas: number;
}

/** Exact integer halalas → "123.45" (never float math). */
export function formatHalalas(halalas: number): string {
  if (!Number.isSafeInteger(halalas) || halalas < 0) {
    throw new Error(`expected non-negative integer halalas, got ${halalas}`);
  }
  const sar = Math.trunc(halalas / 100);
  const cents = halalas % 100;
  return `${sar}.${String(cents).padStart(2, "0")}`;
}

/** Half-up rounding of (amount × percent / 100) on integer halalas. */
function vatOf(amountHalalas: number, vatPercent: number): number {
  // percent scaled to integer basis points to stay in integer arithmetic
  const bp = Math.round(vatPercent * 100);
  return Math.round((amountHalalas * bp) / 10_000);
}

const XML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&apos;",
};

function escapeXml(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => XML_ESCAPES[ch]!);
}

/** Replace every occurrence of a placeholder with an escaped value. */
function fill(template: string, values: Record<string, string>): string {
  let out = template;
  for (const [placeholder, value] of Object.entries(values)) {
    out = out.split(placeholder).join(value);
  }
  return out;
}

function categoryIdFor(vatPercent: number): string {
  return vatPercent > 0 ? "S" : "O";
}

export function buildSimplifiedInvoiceXml(
  props: SimplifiedInvoiceProps,
): BuiltSimplifiedInvoice {
  if (props.lines.length === 0) {
    throw new Error("an invoice requires at least one line");
  }

  interface LineTotals {
    line: ZatcaInvoiceLine;
    subtotalHalalas: number;
    taxHalalas: number;
  }

  const lineTotals: LineTotals[] = props.lines.map((line) => {
    if (!Number.isSafeInteger(line.unitPriceHalalas) || line.unitPriceHalalas < 0) {
      throw new Error(
        `line ${line.id}: unitPriceHalalas must be a non-negative integer (got ${line.unitPriceHalalas})`,
      );
    }
    if (!Number.isSafeInteger(line.quantity) || line.quantity <= 0) {
      throw new Error(
        `line ${line.id}: quantity must be a positive integer (got ${line.quantity})`,
      );
    }
    const subtotalHalalas = line.quantity * line.unitPriceHalalas;
    return {
      line,
      subtotalHalalas,
      taxHalalas: vatOf(subtotalHalalas, line.vatPercent),
    };
  });

  const taxExclusiveHalalas = lineTotals.reduce((s, l) => s + l.subtotalHalalas, 0);
  const taxHalalas = lineTotals.reduce((s, l) => s + l.taxHalalas, 0);
  const taxInclusiveHalalas = taxExclusiveHalalas + taxHalalas;

  // Group lines by (category, percent) for the TaxSubtotal breakdown.
  const groups = new Map<string, { categoryId: string; vatPercent: number; taxable: number; tax: number }>();
  for (const { line, subtotalHalalas, taxHalalas: lineTax } of lineTotals) {
    const categoryId = categoryIdFor(line.vatPercent);
    const key = `${categoryId}:${line.vatPercent}`;
    const group = groups.get(key) ?? {
      categoryId,
      vatPercent: line.vatPercent,
      taxable: 0,
      tax: 0,
    };
    group.taxable += subtotalHalalas;
    group.tax += lineTax;
    groups.set(key, group);
  }

  const allowanceCategories = lineTotals
    .map(({ line }) =>
      fill(ALLOWANCE_TAX_CATEGORY_TEMPLATE, {
        SET_CATEGORY_ID: categoryIdFor(line.vatPercent),
        // The golden sample renders this percent without decimals.
        SET_CATEGORY_PERCENT: String(line.vatPercent),
      }),
    )
    .join("\n");

  const taxSubtotals = [...groups.values()]
    .map((group) =>
      fill(TAX_SUBTOTAL_TEMPLATE, {
        SET_TAXABLE_AMOUNT: formatHalalas(group.taxable),
        SET_SUBTOTAL_TAX_AMOUNT: formatHalalas(group.tax),
        SET_CATEGORY_ID: group.categoryId,
        SET_CATEGORY_PERCENT: group.vatPercent.toFixed(2),
      }),
    )
    .join("\n");

  const invoiceLines = lineTotals
    .map(({ line, subtotalHalalas, taxHalalas: lineTax }) =>
      fill(INVOICE_LINE_TEMPLATE, {
        SET_LINE_ID: String(line.id),
        SET_LINE_QUANTITY: line.quantity.toFixed(6),
        SET_LINE_EXTENSION: formatHalalas(subtotalHalalas),
        SET_LINE_TAX_AMOUNT: formatHalalas(lineTax),
        SET_LINE_ROUNDING_AMOUNT: formatHalalas(subtotalHalalas + lineTax),
        SET_LINE_NAME: escapeXml(line.name),
        SET_CATEGORY_ID: categoryIdFor(line.vatPercent),
        SET_CATEGORY_PERCENT: line.vatPercent.toFixed(2),
        SET_LINE_PRICE: formatHalalas(line.unitPriceHalalas),
      }),
    )
    .join("\n");

  const customerParty = props.customer
    ? fill(CUSTOMER_PARTY_TEMPLATE, {
        SET_CUSTOMER_STREET: escapeXml(props.customer.street),
        SET_CUSTOMER_BUILDING: escapeXml(props.customer.building),
        SET_CUSTOMER_CITY_SUBDIVISION: escapeXml(props.customer.citySubdivision),
        SET_CUSTOMER_CITY: escapeXml(props.customer.city),
        SET_CUSTOMER_POSTAL_ZONE: escapeXml(props.customer.postalZone),
        SET_CUSTOMER_VAT_NUMBER: escapeXml(props.customer.vatNumber),
        SET_CUSTOMER_NAME: escapeXml(props.customer.name),
      })
    : // UBL 2.1 makes the element mandatory; anonymous B2C keeps it empty.
      "    <cac:AccountingCustomerParty></cac:AccountingCustomerParty>";

  const note = props.note
    ? `    <cbc:Note languageID="${escapeXml(props.note.languageId)}">${escapeXml(props.note.text)}</cbc:Note>\n`
    : "";

  const billingReference = props.billingReference
    ? "    <cac:BillingReference>\n" +
      "        <cac:InvoiceDocumentReference>\n" +
      `            <cbc:ID>Invoice Number: ${escapeXml(props.billingReference)}</cbc:ID>\n` +
      "        </cac:InvoiceDocumentReference>\n" +
      "    </cac:BillingReference>\n"
    : "";

  const instructionNote = props.instructionNote
    ? `        <cbc:InstructionNote>${escapeXml(props.instructionNote)}</cbc:InstructionNote>\n`
    : "";

  const xml = fill(SIMPLIFIED_INVOICE_TEMPLATE, {
    SET_INVOICE_SERIAL_NUMBER: escapeXml(props.serialNumber),
    SET_INVOICE_UUID: escapeXml(props.uuid),
    SET_ISSUE_DATE: escapeXml(props.issueDate),
    SET_ISSUE_TIME: escapeXml(props.issueTime),
    SET_INVOICE_TYPE_NAME: escapeXml(props.invoiceTypeName ?? "0200000"),
    SET_INVOICE_TYPE_CODE: escapeXml(props.invoiceTypeCode ?? "388"),
    SET_NOTE: note,
    SET_INVOICE_COUNTER: String(props.icv),
    SET_PREVIOUS_INVOICE_HASH: escapeXml(props.pih),
    SET_SUPPLIER_CRN: escapeXml(props.supplier.crn),
    SET_SUPPLIER_STREET: escapeXml(props.supplier.street),
    SET_SUPPLIER_BUILDING: escapeXml(props.supplier.building),
    SET_SUPPLIER_CITY_SUBDIVISION: escapeXml(props.supplier.citySubdivision),
    SET_SUPPLIER_CITY: escapeXml(props.supplier.city),
    SET_SUPPLIER_POSTAL_ZONE: escapeXml(props.supplier.postalZone),
    SET_SUPPLIER_VAT_NUMBER: escapeXml(props.supplier.vatNumber),
    SET_SUPPLIER_NAME: escapeXml(props.supplier.name),
    SET_CUSTOMER_PARTY: customerParty,
    SET_BILLING_REFERENCE: billingReference,
    SET_PAYMENT_MEANS_CODE: escapeXml(props.paymentMeansCode ?? "10"),
    SET_INSTRUCTION_NOTE: instructionNote,
    SET_ALLOWANCE_TAX_CATEGORIES: allowanceCategories,
    SET_TAX_TOTAL: formatHalalas(taxHalalas),
    SET_TAX_SUBTOTALS: taxSubtotals,
    SET_LINE_EXTENSION_TOTAL: formatHalalas(taxExclusiveHalalas),
    SET_TAX_EXCLUSIVE_TOTAL: formatHalalas(taxExclusiveHalalas),
    SET_TAX_INCLUSIVE_TOTAL: formatHalalas(taxInclusiveHalalas),
    SET_PAYABLE_AMOUNT: formatHalalas(taxInclusiveHalalas),
    SET_INVOICE_LINES: invoiceLines,
  });

  return { xml, taxExclusiveHalalas, taxHalalas, taxInclusiveHalalas };
}
